version: '3.7'

volumes:
    postgres:
    pgadmin:

services:
  postgres:
    container_name: demo_postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
       - postgres:/data/postgres
    ports:
      - "15432:5432"
    restart: unless-stopped
