version: '3.7'

volumes:
    postgres:
    pgadmin:

services:
  postgres:
    container_name: demo_postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: "${DB_PASS:-password}"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped

  api:
    container_name: webapi
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=demo_postgres
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - 5000:5000